In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from tensorflow.keras.models import Sequential


In [ ]:
def one_hot_encoding(protein_seq):
    amino_acids = 'ACDEFGHIKLMNPQRSTVWY'
    aa_dict = {amino_acids[i]: i for i in range(len(amino_acids))}
    num_aa = len(aa_dict)

    max_seq_len = max(len(seq) for seq in protein_seq)
    one_hot = np.zeros((len(protein_seq), max_seq_len, num_aa))

    for i, seq in enumerate(protein_seq):
        for j, aa in enumerate(seq):
            one_hot[i, j, aa_dict[aa]] = 1

    return one_hot
#3D array of one-hot encoding
#len(prtein_seq) = number of sequences in data
#max_seq_len = maximum length of sequence
#num_aa = actual one-hot or number of aminoacid

In [ ]:
# load protein sequence data
protein_data = pd.read_csv("/content/Protein.csv") #Data in excel/csv. two columns "sequence" and "label" 

# convert protein sequences to one-hot encoding
protein_seqs = protein_data["sequence"].tolist()
one_hot = one_hot_encoding(protein_seqs)

# pad sequences to same length
padded_seqs = pad_sequences(one_hot, padding='post', maxlen=1000) #set maxlen value as per the longest lenght of protein sequence in your data


In [ ]:
print(padded_seqs.shape)

(8, 1000, 20)


In [ ]:
print(padded_seqs)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [1 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 1 0 0]
  [0 1 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [1 0 0 ... 0 0 0]
  [0 0 0 ... 1 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [ ]:
# define CNN model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, activation='relu', input_shape=(1000, 20)))
model.add(MaxPooling1D(pool_size=2))
model.add(Conv1D(filters=64, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Conv1D(filters=128, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(units=128, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(units=1, activation='sigmoid'))

# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [ ]:
# train the model
model.fit(padded_seqs, protein_data["label"], epochs=10, batch_size=64, validation_split=0.2)


Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 0.7052 - accuracy: 0.3333 - val_loss: 0.3378 - val_accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 123ms/step - loss: 0.4629 - accuracy: 0.5000 - val_loss: -0.1192 - val_accuracy: 0.0000e+00
Epoch 3/10
1/1 [==============================] - 0s 93ms/step - loss: 0.2081 - accuracy: 0.5000 - val_loss: -0.8329 - val_accuracy: 0.0000e+00
Epoch 4/10
1/1 [==============================] - 0s 122ms/step - loss: -0.2457 - accuracy: 0.5000 - val_loss: -1.9086 - val_accuracy: 0.0000e+00
Epoch 5/10
1/1 [==============================] - 0s 106ms/step - loss: -0.8133 - accuracy: 0.5000 - val_loss: -3.4317 - val_accuracy: 0.0000e+00
Epoch 6/10
1/1 [==============================] - 0s 103ms/step - loss: -1.5280 - accuracy: 0.5000 - val_loss: -5.5400 - val_accuracy: 0.0000e+00
Epoch 7/10
1/1 [==============================] - 0s 127ms/step - loss: -2.4366 - accuracy: 0.5000 - val_loss: -8.4518 - val_accurac